### ISSUE TITLE
Error en startCheckout

### ISSUE THREAD

**Issue by ingsoto83** [Gazer/px-flutter#5]
Al llamar al metodo MercadoPagoMobileCheckout.startCheckout
Me genera el siguiente error:
```
D/MercadoPagoPlugin(28363): Starting checkout for 161011558-ce57ac86-1642-4f02-8e62-9760dff7dc8b
E/flutter (28363): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(0, Not ready, null)
E/flutter (28363): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (28363): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (28363): <asynchronous suspension>
E/flutter (28363): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (28363): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter (28363): #4      MercadoPagoMobileCheckout.startCheckout (package:mercado_pago_mobile_checkout/mercado_pago_mobile_checkout.dart:18:50)
E/flutter (28363): #5      SendRequestScreenState.goToCheckOut (package:figuras_deportivas_net/screens/figures/common/send_request_screen.dart:524:52)
E/flutter (28363): #6      SendRequestScreenState._submit (package:figuras_deportivas_net/screens/figures/common/send_request_screen.dart:431:7)
E/flutter (28363): #7      SendRequestScreenState.build.<anonymous closure> (package:figuras_deportivas_net/screens/figures/common/send_request_screen.dart:404:43)
E/flutter (28363): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (28363): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (28363): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (28363): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (28363): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (28363): #13     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (28363): #14     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (28363): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (28363): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (28363): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (28363): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (28363): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (28363): #20     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (28363): #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (28363): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (28363): #23     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (28363): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

```

**Comment by Gazer** [comment]
Por alguna razón el startCheckout está siendo ejecutado antes de que el plugin esté completamente inicializado (basicamente que tenga una activity). Que versión de flutter estás usando?

**Comment by ingsoto83** [comment]
```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [VersiÃ³n 10.0.18362.836], locale es-MX)
    • Flutter version 1.17.1 at D:\flutter_sdk
    • Framework revision f7a6a7906b (3 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
```

Dejame actualizo a ver si con eso queda

**Comment by ingsoto83** [comment]
Con la nueva versión ya funcionó correctamente!
